export const adminFieldLabels: Record<string, string> = {
  minutes: "นาที",
  goals: "ประตู",
  sourceAssists: "Assist จากไทยลีก",
  fantasyAssists: "Fantasy Assist",
  goalsConcededWhilePlaying: "เสียประตูขณะอยู่ในสนาม",
  saves: "เซฟ",
  penaltySaves: "เซฟจุดโทษ",
  penaltyMisses: "ยิงจุดโทษพลาด",
  yellowCards: "ใบเหลือง",
  redCards: "ใบแดง",
  ownGoals: "ทำเข้าประตูตัวเอง",
  level: "ระดับ",
  isThai: "สถานะไทย",
  reason: "เหตุผล",
  effectiveGameweekId: "Gameweek ที่มีผล",
  status: "สถานะ",
  number: "Gameweek",
  nextGameweek: "Gameweek ถัดไป",
};

export const adminTranslations: Record<string, string> = {
  แสดงข้อมูล: "View data",
  ปรับระดับนักเตะตามรายการ: "Apply tier changes",
  นำเข้าการแก้ไขจากเอกสารนักเตะ: "Apply reviewed player sheet",
  เผยแพร่ชุดจัดอันดับนักเตะ: "Publish player ranking",
  "รายการนี้ไม่มีรายละเอียดค่าก่อน–หลังที่แสดงได้":
    "No displayable before/after values were recorded for this operation.",
  "ยืนยันคะแนน Final": "Finalize scores",
  รอแข่งขัน: "Scheduled",
  กำลังแข่งขัน: "Live",
  จบการแข่งขัน: "Finished",
  เลื่อนการแข่งขัน: "Postponed",
  ยกเลิกการแข่งขัน: "Cancelled",
  บันทึกสำเร็จ: "Saved successfully",
  สถานะ: "Status",
  "Assist จากไทยลีก": "Thai League assists",
  "Fantasy Assist (เว้นว่างเพื่อใช้ต้นทาง)":
    "Fantasy assists (blank uses source)",
  เสียประตูขณะอยู่ในสนาม: "Goals conceded while playing",
  เซฟ: "Saves",
  เซฟจุดโทษ: "Penalty saves",
  ยิงจุดโทษพลาด: "Penalty misses",
  ใบเหลือง: "Yellow cards",
  ใบแดง: "Red cards",
  ทำเข้าประตูตัวเอง: "Own goals",
  บันทึกและคำนวณคะแนนใหม่: "Save and recalculate scores",
  "เหตุผล/แหล่งอ้างอิง": "Reason / reference",
  ค้นหา: "Search",
  ตำแหน่ง: "Position",
  ตัวจริง: "Starter",
  ค้นหานักเตะ: "Search players",
  สโมสร: "Club",
  "มีผลตั้งแต่ Gameweek": "Effective from Gameweek",
  บันทึกระดับและสถานะ: "Save classification",
  สถานะสัญชาติ: "Nationality status",
  "ไทย/ลูกครึ่งไทย": "Thai / Thai heritage",
  เหตุผล: "Reason",
  ภาพรวม: "Overview",
  ผู้ดูแลระบบ: "Administrator",
  ผู้เล่นและทีม: "Participants & teams",
  ผลการแข่งขันและสถิติ: "Matches & stats",
  ข้อมูลนักเตะ: "Player data",
  ประวัติการแก้ไข: "Audit history",
  กลับโหมดผู้เล่น: "Back to player mode",
  "ติดตามผู้เล่นและงานที่ต้องจัดการในฤดูกาล 2026/27":
    "Track participants and operations for the 2026/27 season",
  ดูข้อมูล: "View data",
  ทีมทั้งหมด: "All teams",
  ทีมสมาชิก: "Member teams",
  "ทีม Guest": "Guest teams",
  "ทีม Bot": "Bot teams",
  "มีการจัดทีมใน 7 วัน": "Team activity in 7 days",
  "จัดครบ 15 คน": "15-player squads",
  "ยังไม่ครบ / ทีมไม่ใช้งาน": "Incomplete / inactive teams",
  "Guest เก็บประวัติ": "Preserved Guest teams",
  "นับเป็นทีมในฤดูกาล ไม่ใช่จำนวนคนไม่ซ้ำ กิจกรรม 7 วันนับการบันทึกหรือย้อนการจัดทีมของสมาชิกและ Guest ไม่รวม Bot และการยกทีมอัตโนมัติ":
    "Counts represent season teams, not unique people. Seven-day activity counts member and Guest saves or reverts, excluding bots and automatic carryover.",
  "จัดครบ 15 คนนับรวมทีมที่ยกมาจาก GW ก่อนหน้า ไม่ได้หมายถึงเข้ามาเล่นล่าสุดหรือผ่านการตรวจทุกกติกา":
    "15-player squads include automatic carryover. This does not imply recent activity or validation against every squad rule.",
  งานรอดำเนินการ: "Pending operations",
  "จัดการ Gameweek": "Manage Gameweek",
  "ไม่มี Gameweek ที่รอดำเนินการ": "No Gameweeks need attention",
  ตรวจข้อมูลการแข่งขัน: "Review match data",
  "เลือกคู่แข่งขันเพื่อตรวจสถิติและแก้ไขคะแนน หรือทบทวนประวัติการเปลี่ยนแปลง":
    "Select a match to review stats and correct scores, or inspect the change history.",
  "ค้นหาทีมและดูการมีส่วนร่วม แยกสมาชิก Guest และ Bot":
    "Find teams and review participation by members, Guests and bots",
  ค้นหาชื่อทีม: "Search team names",
  ประเภททีม: "Team type",
  ทุกประเภท: "All types",
  การจัดทีม: "Squad activity",
  ทีมไม่ใช้งาน: "Inactive team",
  รายชื่อทีม: "Team list",
  "คะแนน GW": "GW points",
  บันทึกทีมล่าสุด: "Last team save",
  ล้างตัวกรอง: "Clear filters",
  "กิจกรรมล่าสุดนับการบันทึกและย้อนการจัดทีม ไม่ใช่การเข้าชมเว็บ จำนวนทีมไม่ใช่จำนวนคนไม่ซ้ำ":
    "Recent activity counts team saves and reverts, not page visits. Team counts do not represent unique people.",
  รายละเอียดทีม: "Team details",
  "ตรวจทีมที่บันทึกไว้และคะแนนใน Gameweek ที่เลือก":
    "Inspect saved squads and scores for the selected Gameweek",
  กลับรายชื่อทีม: "Back to teams",
  คะแนนรวมฤดูกาล: "Season points",
  ระดับที่บันทึก: "Saved tier",
  บทบาทในทีม: "Squad role",
  "ยังไม่มีนักเตะที่บันทึกใน Gameweek นี้": "No saved squad for this Gameweek",
  "ตรวจสถานะและ Deadline ก่อนล็อกทีม หรือยืนยันคะแนน Final":
    "Review status and deadlines before locking squads or finalizing scores",
  "Deadline (เวลาไทย)": "Deadline (Bangkok time)",
  คะแนนเฉลี่ย: "Average points",
  คะแนนสูงสุด: "Highest points",
  ล็อกทีมและปิดรับจัดทีม: "Lock squads and close entries",
  "การล็อกมีผลกับทุกทีม และเปิด Gameweek ถัดไปหากยังไม่จบฤดูกาล":
    "Locking affects every team and opens the next Gameweek unless the season has ended.",
  ตรวจสถิติและการแก้ไขทั้งหมดก่อนยืนยันคะแนน:
    "Review all match stats and corrections before finalizing scores.",
  "Gameweek นี้ยืนยันคะแนนแล้ว": "This Gameweek is finalized",
  "ยังไม่มีการดำเนินการที่พร้อมสำหรับ Gameweek นี้":
    "No operation is available for this Gameweek yet",
  "Gameweek ทั้งฤดูกาล": "Season Gameweeks",
  ยังไม่เปิด: "Planned",
  เปิดรับจัดทีม: "Open for squad changes",
  รอตรวจคะแนน: "Provisional scores",
  "คะแนน Final": "Final scores",
  ล็อกแล้ว: "Locked",
  "เลือก Gameweek คู่แข่งขัน และนักเตะ แล้วตรวจค่าปัจจุบันก่อนบันทึกและคำนวณคะแนนใหม่":
    "Select a Gameweek, match and player, then review the current values before saving and recalculating scores",
  นักเตะในคู่แข่งขัน: "Match players",
  โหลดสถิติ: "Load stats",
  "ยังไม่มีสถิติที่บันทึกไว้ ระบบจะสร้างรายการใหม่":
    "No stats have been saved. Saving will create a new record.",
  "ยังไม่มีการแข่งขันหรือนักเตะใน Gameweek นี้":
    "No matches or players for this Gameweek",
  "ค้นหานักเตะและกำหนดระดับหรือสถานะไทย ตั้งแต่ Gameweek ที่เลือก":
    "Find players and set their tier for the selected Gameweek or update Thai status",
  เหตุผลและแหล่งอ้างอิงสำหรับการเปลี่ยนแปลง:
    "Reason and reference for this change",
  ไม่พบนักเตะที่ตรงกับตัวกรอง: "No players match these filters",
  โหลดข้อมูล: "Load data",
  ทุกระดับ: "All tiers",
  "ตรวจรายการที่บันทึกไว้ ผู้ดำเนินการ เหตุผล และค่าก่อน–หลัง":
    "Review recorded operations, operators, reasons and before/after values",
  การดำเนินการ: "Operation",
  บันทึกสถิติใหม่: "Create match stats",
  แก้ไขสถิติ: "Correct match stats",
  ปรับระดับและสถานะ: "Update classification",
  "ล็อก Gameweek": "Lock Gameweek",
  "สร้างทีม Bot": "Create bot team",
  ผู้ดำเนินการ: "Operator",
  รายการที่แก้ไข: "Affected record",
  "แสดงเฉพาะประวัติที่ระบบบันทึกไว้ การล็อกและ Final ก่อนเริ่มเก็บประวัติจะไม่ปรากฏ":
    "Only recorded operations are shown. Locks and finalizations performed before audit collection are not available.",
  ยังไม่มีประวัติในตัวกรองนี้: "No history matches this filter",
  ไม่พบข้อมูลที่ตรงกับตัวกรอง: "No results match these filters",
  ยังไม่มีข้อมูล: "No data yet",
  แบ่งหน้า: "Pagination",
  หน้า: "Page",
  ก่อนหน้า: "Previous",
  ถัดไป: "Next",
  "บันทึกไม่สำเร็จ ตรวจสอบข้อมูลและสถานะล่าสุดก่อนลองอีกครั้ง":
    "Could not save. Review the data and current status before trying again.",
  กลับไปตรวจสอบ: "Review again",
  ยืนยันการบันทึก: "Confirm save",
  สถานะไทย: "Thai status",
  "Gameweek ที่มีผล": "Effective Gameweek",
  "Gameweek ถัดไป": "Next Gameweek",
  "ข้อมูลที่แก้ไขจะหายไป หากออกจากหน้านี้โดยไม่บันทึก":
    "Your changes will be lost if you leave this page without saving.",
};
