export type FantasyPlayer = {
  id: number;
  name: string;
  club: string;
  position: "GK" | "DEF" | "MID" | "FWD";
  price: number;
  points: number;
  form: number;
  selected: number;
  next: string;
  color: string;
  accent: string;
  trend: "up" | "down" | "same";
};

export const playerPool: FantasyPlayer[] = [
  {
    id: 1,
    name: "ชนาธิป สรงกระสินธ์",
    club: "บีจี ปทุม",
    position: "MID",
    price: 10,
    points: 14,
    form: 8.4,
    selected: 41.2,
    next: "ลำพูน (H)",
    color: "#2364a4",
    accent: "#e72530",
    trend: "up",
  },
  {
    id: 2,
    name: "ธีราทร บุญมาทัน",
    club: "บุรีรัมย์ ยูไนเต็ด",
    position: "MID",
    price: 9,
    points: 11,
    form: 7.8,
    selected: 38.6,
    next: "เชียงราย (H)",
    color: "#17264f",
    accent: "#ffdc28",
    trend: "up",
  },
  {
    id: 3,
    name: "บดินทร์ ผาลา",
    club: "การท่าเรือ",
    position: "MID",
    price: 8,
    points: 9,
    form: 7.1,
    selected: 24.8,
    next: "ราชบุรี (A)",
    color: "#f58220",
    accent: "#153f7a",
    trend: "up",
  },
  {
    id: 4,
    name: "ศุภชัย ใจเด็ด",
    club: "บุรีรัมย์ ยูไนเต็ด",
    position: "FWD",
    price: 9,
    points: 8,
    form: 6.9,
    selected: 35.3,
    next: "เชียงราย (H)",
    color: "#17264f",
    accent: "#ffdc28",
    trend: "same",
  },
  {
    id: 5,
    name: "พรรษา เหมวิบูลย์",
    club: "บุรีรัมย์ ยูไนเต็ด",
    position: "DEF",
    price: 5.5,
    points: 8,
    form: 6.6,
    selected: 29.1,
    next: "เชียงราย (H)",
    color: "#17264f",
    accent: "#ffdc28",
    trend: "up",
  },
  {
    id: 6,
    name: "ศุภนันท์ บุรีรัตน์",
    club: "การท่าเรือ",
    position: "DEF",
    price: 5.5,
    points: 7,
    form: 6.2,
    selected: 18.7,
    next: "ราชบุรี (A)",
    color: "#f58220",
    accent: "#153f7a",
    trend: "up",
  },
  {
    id: 7,
    name: "ปฏิวัติ คำไหม",
    club: "ทรู แบงค็อก",
    position: "GK",
    price: 5,
    points: 6,
    form: 5.9,
    selected: 21.4,
    next: "เมืองทอง (H)",
    color: "#d81f34",
    accent: "#182247",
    trend: "same",
  },
  {
    id: 8,
    name: "สุภโชค สารชาติ",
    club: "คอนซาโดเล ซัปโปโร",
    position: "MID",
    price: 9.5,
    points: 6,
    form: 5.7,
    selected: 31.6,
    next: "นครราชสีมา (A)",
    color: "#d71935",
    accent: "#171b39",
    trend: "down",
  },
  {
    id: 9,
    name: "ธีรศิลป์ แดงดา",
    club: "บีจี ปทุม",
    position: "FWD",
    price: 8.5,
    points: 5,
    form: 5.4,
    selected: 27.9,
    next: "ลำพูน (H)",
    color: "#2364a4",
    accent: "#e72530",
    trend: "down",
  },
  {
    id: 10,
    name: "นิโคลัส มิคเคลสัน",
    club: "โอเดนเซ",
    position: "DEF",
    price: 5,
    points: 5,
    form: 5.1,
    selected: 15.8,
    next: "สุโขทัย (A)",
    color: "#ffffff",
    accent: "#e2242d",
    trend: "same",
  },
  {
    id: 11,
    name: "ปรเมศย์ อาจวิไล",
    club: "เมืองทอง ยูไนเต็ด",
    position: "FWD",
    price: 6.5,
    points: 4,
    form: 4.8,
    selected: 9.7,
    next: "แบงค็อก (A)",
    color: "#d62232",
    accent: "#111111",
    trend: "up",
  },
  {
    id: 12,
    name: "สรานนท์ อนุอินทร์",
    club: "เชียงราย ยูไนเต็ด",
    position: "GK",
    price: 4.5,
    points: 3,
    form: 4.2,
    selected: 7.3,
    next: "บุรีรัมย์ (A)",
    color: "#f25c34",
    accent: "#25295f",
    trend: "down",
  },
  {
    id: 13,
    name: "เอเลียส ดอเลาะ",
    club: "การท่าเรือ",
    position: "DEF",
    price: 5,
    points: 4,
    form: 4.9,
    selected: 12.5,
    next: "ราชบุรี (A)",
    color: "#f58220",
    accent: "#153f7a",
    trend: "same",
  },
  {
    id: 14,
    name: "พิธิวัตต์ สุขจิตธรรมกุล",
    club: "บุรีรัมย์ ยูไนเต็ด",
    position: "MID",
    price: 6,
    points: 3,
    form: 4.4,
    selected: 8.2,
    next: "เชียงราย (H)",
    color: "#17264f",
    accent: "#ffdc28",
    trend: "up",
  },
  {
    id: 15,
    name: "จักพัน ไพรสุวรรณ",
    club: "บีจี ปทุม",
    position: "DEF",
    price: 4.5,
    points: 2,
    form: 3.8,
    selected: 5.9,
    next: "ลำพูน (H)",
    color: "#2364a4",
    accent: "#e72530",
    trend: "same",
  },
];

export const leagueTable = [
  {
    rank: 1,
    name: "Siam Strikers",
    manager: "Nattapong S.",
    gw: 82,
    total: 82,
    movement: 2,
  },
  {
    rank: 2,
    name: "Bangkok Ballers",
    manager: "Kawin P.",
    gw: 78,
    total: 78,
    movement: -1,
  },
  {
    rank: 3,
    name: "PIYA FC",
    manager: "Piyawat K.",
    gw: 67,
    total: 67,
    movement: 4,
    mine: true,
  },
  {
    rank: 4,
    name: "Isan United",
    manager: "Thanawat C.",
    gw: 65,
    total: 65,
    movement: 1,
  },
  {
    rank: 5,
    name: "Southern Waves",
    manager: "Akarin T.",
    gw: 62,
    total: 62,
    movement: -2,
  },
  {
    rank: 6,
    name: "Lanna Eleven",
    manager: "Phurin J.",
    gw: 59,
    total: 59,
    movement: 0,
  },
  {
    rank: 7,
    name: "Chonburi Sharks",
    manager: "Methas K.",
    gw: 55,
    total: 55,
    movement: -1,
  },
];

export const fixtures = [
  {
    time: "18:00",
    home: "บุรีรัมย์ ยูไนเต็ด",
    away: "เชียงราย ยูไนเต็ด",
    homeShort: "BRU",
    awayShort: "CRU",
    difficulty: 2,
    channel: "AIS PLAY",
  },
  {
    time: "18:30",
    home: "บีจี ปทุม",
    away: "ลำพูน วอริเออร์",
    homeShort: "BGP",
    awayShort: "LPW",
    difficulty: 2,
    channel: "True Ball Thai 1",
  },
  {
    time: "19:00",
    home: "ทรู แบงค็อก",
    away: "เมืองทอง ยูไนเต็ด",
    homeShort: "BUFC",
    awayShort: "MTUTD",
    difficulty: 4,
    channel: "True Ball Thai 2",
  },
  {
    time: "19:30",
    home: "ราชบุรี เอฟซี",
    away: "การท่าเรือ",
    homeShort: "RBFC",
    awayShort: "PORT",
    difficulty: 3,
    channel: "AIS PLAY",
  },
];
